project_id = "mgveeoqkhthibpmmljxz"

[functions.analyze-threat]
verify_jwt = false

[functions.waf-proxy]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.auto-setup-waf]
verify_jwt = false
